### ISSUE TITLE
wrong number of type arguments

### ISSUE THREAD

**Issue by anowell** [djc/askama#29]
I hit this when upgrading from ffc74a17 to 8bda0d64. I haven't had time to dig in yet, (will try and set aside some time tomorrow if you haven't magically fixed it by then), but I thought I'd give you a quick heads up (i.e. hold off on publishing the updates to crates.io).

```
error[E0244]: wrong number of type arguments: expected 1, found 2
   --> src/templates/mod.rs:139:10
    |
139 | #[derive(Template)]
    |          ^^^^^^^^ expected 1 type argument
```

**Comment by djc** [comment]
If you can just copy/paste struct definitions and the template in, I'm happy to figure it out from there!

**Comment by anowell** [comment]
Sorry, I got buried. I can repro it with this in my project:

```
    #[derive(Template)]
    #[template(path = "foo.j2")]
    struct Foo<'a> {
        text: &'a str,
    }
```

but your tests seem to basically cover that scenario and they pass for me. Only seems to happen for me in a specific module, so it seems like I have something else conflicting with it. Actively digging into this now...

**Comment by anowell** [comment]
Aha!

I'm using `error_chain` for error boilerplate, which provides a type-aliased `Result` by default, so I have an `::error::Result<T>` that is a type alias for `::std::result::Result<T, ::error::Error>`. I pretty much do `use error::*` in every file, and so when something in your macro generates `Result<T, E>`, since my type-aliased `Result` is in scope, it only wants one type arg instead of two.

**Comment by djc** [comment]
Ah, so it should go away if I use the full path to `Result` in code gen. Want to take a whack at a patch? Just search and replace in `generator.rs`.

**Comment by anowell** [comment]
for sure - and I already have another PR incoming shortly ;-)

**Comment by anowell** [comment]
fyi: the recent changes are more generally backward-incompatible on two grounds:

1. `render()` previously returned a `String`, but now returns `Result<String, fmt::Error>`.
2. Importing `askama::Template` is now required to use the derive macro (that wasn't the case previously)

I'm perfectly fine fixing my code if these are intentional - I just wanted to point them out and suggest that the next published version be 0.4.0 for the sake of Cargo's semver (i.e. I hit 37 [easy-to-fix] compile errors).

**Comment by djc** [comment]
Yeah, was definitely aware of the former and planning to release as 0.4.0. I'm surprised that the latter was not necessary before... 

I will also write up a changelog in the GitHub releases page, as I did before, once it gets released.

**Comment by djc** [comment]
I was thinking about this a bit more, would you be able to bisect what commit started to require the import of `Template`? I'm curious because I thought it was always needed, but apparently some users might not have used it.

**Comment by anowell** [comment]
Yeah. I can bisect it tonight. Off the top of my head, it seemed related to the `render_into` usage within the macro needing a trait in scope, so I'm gonna guess [this line](https://github.com/djc/askama/blob/5f3e93da3f1815f24b82b026b95e748267d1b5e8/askama_derive/src/generator.rs#L485) is the cause, which is the only line I see in the generated code that obviously depends on the trait being in scope.

You could generate with `use ::askama::Template` included, but I think you'd need to rename the import to something random to avoid colliding with a user's existing imports (or multiple `derive(Template)` in the same scope), e.g. `"use ::askama::Template as Template_{}", uuid`. I only know this because I have a macro pumping out templates that had import collisions until I added a snippet like that.

**Comment by djc** [comment]
Ah, that makes sense. Well, I had documented the requirement of adding `use askama::Template`, so I'd rather have that as a requirement than a convoluted work around with randomized identifiers.

**Comment by anowell** [comment]
Yeah. I probably had `use askama::Template` originally because of the documentation, but since I call `render()` from a different module, the compiler warned of an unused import, so I had removed it until the `Display` stuff landed. :-)

On one hand, I can see the argument for a random identifier since derive macros like serde don't require `use serde::Serialize`, but I think the namespaced macros of the future will remove the need for `#[macro_use]` and re-introduce the need for importing the macro with `use`, so I don't mind either way, and you're probably on the more future-proof side.
