### ISSUE TITLE
Regression in askama_parser 0.2.0 update

### ISSUE THREAD

**Issue by c1wren** [djc/askama#935]
Just updated askama_derive to 0.12.4 from 0.12.2 and askama_parser to 0.2.0 from 0.1.1 and now my project fails to compile.

```
error[E0277]: the trait bound `&std::string::String: From<&str>` is not satisfied
   --> askama_templates/src/templates.rs:202:10
    |
202 | #[derive(Template)]
    |          ^^^^^^^^
    |          |
    |          the trait `From<&str>` is not implemented for `&std::string::String`
    |          in this derive macro expansion
    |
   ::: .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/askama_derive-0.12.4/src/lib.rs:22:1
    |
22  | pub fn derive_template(input: TokenStream) -> TokenStream {
    | --------------------------------------------------------- in this expansion of `#[derive(Template)]`
    |
    = help: the following other types implement trait `From<T>`:
              <std::string::String as From<char>>
              <std::string::String as From<bytestring::ByteString>>
              <std::string::String as From<smol_str::SmolStr>>
              <std::string::String as From<Box<str>>>
              <std::string::String as From<uuid::Uuid>>
              <std::string::String as From<Cow<'a, str>>>
              <std::string::String as From<url::Url>>
              <std::string::String as From<sqlx_postgres::types::citext::PgCiText>>
            and 4 others
    = note: required for `&str` to implement `Into<&std::string::String>`
```

My template struct:

```
#[derive(Template)]
#[template(path = "report.html")]
pub struct ReportTemplate<'a> {
    pub report_type: &'a str,
    pub report_date: &'a str,
}
```

**Comment by djc** [comment]
What does `report.html` look like?

**Comment by c1wren** [comment]
@djc I found a minimal reproducible sample. 

If you do something like:
```
    {% let my_string -%}
    {% if true -%}
    {% let my_string = format!("testing {}", true) -%}
    {% else -%}
    {% let my_string = "something else".into() -%}
    {% endif %}

    {{ my_string }}
```

You will get the error. That template code previously worked.

**Comment by djc** [comment]
Right, so this is caused by #922. Reverting that is probably an option, but just the one bug report (so far) doesn't provide a very strong incentive...

**Comment by c1wren** [comment]
I agree that it isn't a strong incentive, but it is technically a breaking change and shouldn't cause code to no longer compile just because someone ran ```cargo update```.

**Comment by djc** [comment]
Unfortunately the power of the code generator makes it pretty hard to notice when that is the case, so I'm more interested in the range of breakage (and how easy the breakage is to work around).

**Comment by c1wren** [comment]
I tried replacing the ```.into()```'s with ```.to_owned()``` or ```.to_string()``` or ```String::from()``` and now I get a different compilation error.

```
error[E0308]: mismatched types
    |
    | #[derive(Template)]
    |          ^^^^^^^^
    |          |
    |          expected `&String`, found `String`
    |          expected due to the type of this binding
```

**Comment by GuillaumeGomez** [comment]
We could potentially mitigate the problem to not make it take a reference if a method is called?

**Comment by djc** [comment]
> We could potentially mitigate the problem to not make it take a reference if a method is called?
> 
> EDIT: Or a function.

Yeah, was thinking about that. Not sure it generalizes well as a heuristic -- there are enough methods/functions that yield references.

**Comment by GuillaumeGomez** [comment]
I'm pretty sure wrapping a call returned behind a reference is never what we want though.

**Comment by djc** [comment]
Hmm, that's fair. Okay, do you want to try it?

**Comment by GuillaumeGomez** [comment]
Sure. Give me a few hours so I can test a few things.

**Comment by GuillaumeGomez** [comment]
I opened https://github.com/djc/askama/pull/937. I think it covers most of this issue here.

**Comment by djc** [comment]
This should be fixed in askama_derive 0.12.5.
