### ISSUE TITLE
Does it work with actix-web 4.0.0-beta.10?

### ISSUE THREAD

**Issue by pashinin** [djc/askama#552]
I have repeated errors:

```
type `Future` is not a member of trait `actix_web::Responder`
...
type `Error` is not a member of trait `actix_web::Responder`
...
7 | #[derive(Template)]
  |          ^^^^^^^^ associated type `Future` not found
...
27 | #[derive(Template)]
   |          ^^^^^^^^ associated type `Error` not found
```

**Comment by djc** [comment]
See #485.
