### ISSUE TITLE
Rocket integration

### ISSUE THREAD

**Issue by mjanda** [djc/askama#65]
Hello,
is Rocket integration working with latest Rocket version? (0.3.6) It seems to be broken since they changed their Responder trait.

It seems to me that builds should be failing now, but Travis isn't running those tests.

**Comment by djc** [comment]
Are you using Askama release or master? Try master, there've been some fixes.

**Comment by mjanda** [comment]
Using master, I'll get

```
error: proc-macro derive panicked
  --> testing/tests/rocket.rs:14:10
   |
14 | #[derive(Template)]
   |          ^^^^^^^^
   |
   = help: message: assertion failed: self.empty_or_trailing()
```

And several other failing tests when running `cargo test --all-features` with `rustc 1.25.0-nightly (3f92e8d89 2018-01-14)`

**Comment by djc** [comment]
I saw these the first time, but then didn't seem them again when I tried running the tests again. Also after running `cargo cleanup` in the testing crate, it seems to work for me. Can you try that? There might be an issue with incremental compilation or something.

**Comment by djc** [comment]
Ah, it turned out there was an issue with the way I used the new syn version. See fb3de4c for more details. Thanks for reporting!

**Comment by mjanda** [comment]
After `cargo clean` and pulling current master, `cargo test --all-features` (btw: how do I run tests with rocket? `cargo test --features "with-rocket"` skips them):

```
error[E0107]: wrong number of lifetime parameters: expected 1, found 2
  --> testing/tests/rocket.rs:14:10
   |
14 | #[derive(Template)]
   |          ^^^^^^^^ unexpected lifetime parameter

error: aborting due to previous error
```

Clearly, it doesn't like `HelloTemplate< 'a , 'r >` declaration, looking for `HelloTemplate< 'r >` instead.

```
impl < 'a , 'r > ::askama::rocket::Responder<'r> for HelloTemplate< 'a , 'r > {
    fn respond_to(self, _: &::askama::rocket::Request) -> ::askama::rocket::Result<'r> {
        ::askama::rocket::respond(&self, "html")
    }
}
```

**Comment by djc** [comment]
Ahh, now it makes sense. a69d060 has improved things.
