### PR TITLE
Fix support for mixed case variables

### LINKED ISSUE #924: 0.12.1 only allow lower-case variable name in template
I don't know if I asked a stupid question, but I spend one day to find it ! my rust version is 1.74.0, I run it on my win11 and WSL ubuntu 22.04, see the same error below
```rust
use askama::Template;

#[derive(Template)] 
#[template(path = "hello.html")]
struct HelloTemplate<'a> {
    nAme: &'a str, 
}
fn main() {
    let hello = HelloTemplate { nAme: "world" }; 
    println!("{}", hello.render().unwrap());
}
```
```html
Hello, {{ nAme }}!
```
```toml
[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[dependencies]
askama="0.12.1"
```
[xxx.DESKTOP-ABCDE12] ⮞ cargo run -p hello
   Compiling hello v0.1.0 (C:\xx\xx\xx\hello)
error[E0425]: cannot find value `nAme` in this scope
 --> hello\src\main.rs:3:10
  |
3 | #[derive(Template)]
  |          ^^^^^^^^
  |
  = note: this error originates in the derive macro `Template` (in Nightly builds, run with -Z macro-backtrace for more info)
help: you might have meant to use the available field
  |
3 | #[derive(self.Template)]
  |          +++++

For more information about this error, try `rustc --explain E0425`.
error: could not compile `hello` (bin "hello") due to previous error

### PR DESCRIPTION
**Pull request by djc**
Fixes #924. Looks like this might have regressed in #840. I think checking only the first letter is a better heuristic than checking if any letters are uppercase.

### CODE REVIEW

File: testing/tests/simple.rs [hunk 1]
```diff
@@ -484,3 +484,16 @@ fn test_num_literals() {
         "[90, -90, 90, 2, 56, 240, 10.5, 10.5, 100000000000, 105000000000]",
     );
 }
+
+#[allow(non_snake_case)]
```
Comment (GuillaumeGomez) [inline testing/tests/simple.rs:488]: Would be nice to add comments explaining what this is testing and also eventually link to the issue.

**Review by GuillaumeGomez — COMMENTED** [review]
Apart from my nit, looks good to me.

File: testing/tests/simple.rs (hunk 1 above)
Comment (djc) [reply testing/tests/simple.rs:488]: Added.

**Review by GuillaumeGomez — APPROVED** [review]
Great, thanks!
