### ISSUE TITLE
Regression between 0.11.0 and 0.11.1

### ISSUE THREAD

**Issue by msrd0** [djc/askama#715]
This project used to build fine with 0.11.0: https://github.com/msrd0/bitmap-font/tree/main/codegen

However, with the latest version 0.11.1 it fails with the following error:

```
error[E0609]: no field `chunks` on type `&RustSource<'a>`
  --> codegen/src/main.rs:40:10
   |
40 | #[derive(Template)]
   |          ^^^^^^^^ unknown field
   |
   = note: available fields are: `char_ranges`, `fonts`
   = note: this error originates in the derive macro `Template` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0609`.
error: could not compile `bitmap-font-codegen` due to previous error
```

I reverted to the old version by pinning askama to 0.11.0, askama_derive to 0.11.0 and askama_shared to 0.12.0 and with those old versions it compiles and runs as expected.

**Comment by djc** [comment]
Would you be able to bisect when/where we broke it?

**Comment by msrd0** [comment]
I don't know how to do a bisect but I could test against some git commits if you tell me relevant ones.

**Comment by Kijewski** [comment]
In [codegen/templates/src.rs.j2:81 ](https://github.com/msrd0/bitmap-font/blob/fbd0c89e81df39715a0dfea41c6ceb933562b1a7/codegen/templates/src.rs.j2#L81) you need to remove the spaces around the pipe `|`.

> Note that the pipe symbol must not be surrounded by spaces; otherwise, it will be interpreted as the BitOr operator.  [§ filters](https://djc.github.io/askama/filters.html)

Your code should not have worked in v0.10. So that is does not compile anymore is actually a bugfix. :)

**Comment by msrd0** [comment]
Thanks @Kijewski, it works with that change
