### ISSUE TITLE
askama_axum v0.2 error with Template

### ISSUE THREAD

**Issue by bouncydingbat** [djc/askama#757]
after update askama_axum to 0.2 (ref #756) i get following error and with the propose use statement

```
error[E0412]: cannot find type `BoxBody` in crate `askama_axum`
  --> mycrate\src\main.rs:11:10
   |
11 | #[derive(Template)]
   |          ^^^^^^^^ not found in `askama_axum`
   |
   = note: this error originates in the derive macro `Template` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this type alias
   |
1  | use axum::body::BoxBody;
   |
help: if you import `BoxBody`, refer to it directly
   |
11 | #[derive(Template)]
```

code similar to example at https://github.com/djc/askama/blob/main/askama_axum/tests/basic.rs

error on `#[derive(Template)]`

```
use askama::Template;
use axum::{
    extract,
    http::StatusCode,
    response::{Html, IntoResponse, Response},
    routing::{get, MethodRouter},
    Router,
};

#[derive(Template)]
#[template(path = "hello.html")]
struct HelloTemplate {
    name: String,
}
```

is why `cargo upgrade` mark update incompatible?

```
name        old req compatible latest new req note        
====        ======= ========== ====== ======= ====
anyhow      1.0.68  1.0.68     1.0.68 1.0.68
askama      0.11.1  0.11.1     0.11.1 0.11.1
askama_axum 0.1.0   0.1.0      0.2.0  0.1.0   incompatible
axum        0.6.1   0.6.1      0.6.1  0.6.1
tokio       1.23.0  1.23.0     1.23.0 1.23.0
```

**Comment by djc** [comment]
It sounds like you have some kind of version mismatch between your dependencies going on.

**Comment by bouncydingbat** [comment]
how do find mismatch? cargo update and cargo upgrade show no changes.

**Comment by dpc** [comment]
Same problem here. Deps versions like @bouncydingbat .

**Comment by tomstoneham** [comment]
I'm having the same issue.

I tried downloading the version of `askama_axum` uploaded to crates.io (using [cargo-download](https://crates.io/crates/cargo-download)), then running `cargo test` and experienced the same error. Here's the full log:

```text
$ cargo download askama_axum > askama_axum.tar.gz
INFO: cargo-download v0.1.2
INFO: Latest version of crate askama_axum=* is 0.2.0
INFO: Crate `askama_axum==0.2.0` downloaded successfully

$ tar -xzvf askama_axum.tar.gz
askama_axum-0.2.0/.cargo_vcs_info.json
askama_axum-0.2.0/Cargo.toml
askama_axum-0.2.0/Cargo.toml.orig
askama_axum-0.2.0/LICENSE-APACHE
askama_axum-0.2.0/LICENSE-MIT
askama_axum-0.2.0/README.md
askama_axum-0.2.0/src/lib.rs
askama_axum-0.2.0/templates/hello.html
askama_axum-0.2.0/tests/basic.rs

$ cd askama_axum-0.2.0

$ cargo test
    Updating crates.io index
   Compiling proc-macro2 v1.0.49
[...] lines removed for brevity
   Compiling askama v0.11.1
   Compiling askama_axum v0.2.0 (/tmp/askama_axum-0.2.0)
   Compiling tokio-util v0.7.4
   Compiling h2 v0.3.15
   Compiling hyper v0.14.23
error[E0412]: cannot find type `BoxBody` in crate `askama_axum`
  --> tests/basic.rs:10:10
   |
10 | #[derive(Template)]
   |          ^^^^^^^^ not found in `askama_axum`
   |
   = note: this error originates in the derive macro `Template` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing one of these items
   |
1  | use axum::body::BoxBody;
   |
1  | use axum_core::body::BoxBody;
   |
help: if you import `BoxBody`, refer to it directly
   |
10 | #[derive(Template)]
   |

For more information about this error, try `rustc --explain E0412`.
error: could not compile `askama_axum` due to previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by tomstoneham** [comment]
I took a look at the version of `askama_shared` uploaded to crates.io, and I think this is the source of the issue: On line 224 of `src/generator.rs` of the published version of the crate, the code to be generated includes `::askama_axum::BoxBody`, which is no longer re-exported by `askama_axum` (it was in 0.1.0, it's not in 0.2.0).

It looks like the version of `askama_shared` in the `0.11.x` branch [shouldn't have this issue](https://github.com/djc/askama/blob/0.11.x/askama_shared/src/generator.rs#L222), so I believe this issue could be resolved by publishing the new version of `askama_shared` to crates.io.

**Comment by djc** [comment]
Changing this in askama_shared in a 0.11.x bump will cause issues for people who are still using older Axum versions. Can someone test if the fix in #758 works?

**Comment by jsmith9999d** [comment]
same problem here and your branch isnt working for me using @bouncydingbat's code.
just bump versions then people can keep their vulnerable code if using old versions and everyone else gets a proper fix?

```
askama = { version = "0.11", default-features = false, features = ["serde-json", "with-axum"] }
askama_axum = { git = "https://github.com/djc/askama.git", branch = "axum-compat" }
```

```
error[E0277]: the trait bound `HelloTemplate: askama_axum::Template` is not satisfied
  --> MYCRATE\src\main.rs:10:10
   |
10 | #[derive(Template)]
   |          ^^^^^^^^ the trait `askama_axum::Template` is not implemented for `HelloTemplate`
   |
note: required by a bound in `askama_axum::into_response`
  --> X:\MYUSER\.cargo\git\checkouts\askama-52332df5234d73e6\6d76ff2\askama_axum\src\lib.rs:10:25
   |
10 | pub fn into_response<T: Template>(t: &T, _ext: &str) -> Response {
   |                         ^^^^^^^^ required by this bound in `askama_axum::into_response`
   = note: this error originates in the derive macro `Template` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `MYCRATE` due to previous error
```

**Comment by tomstoneham** [comment]
@djc Ah of course, sorry! Your fix seems to work for me though, thanks so much for the quick response to this!

@jsmith9999d I think this is due to an incompatibility between the version of askama on crates.io, and the version of askama in the `axum-compat` branch. If I specify both `askama` and `askama_axum` to be retrieved from git, this works for me, like so:

```toml
askama = { git = "https://github.com/djc/askama.git", branch = "axum-compat", features = ["with-axum"] }
askama_axum = { git = "https://github.com/djc/askama.git", branch = "axum-compat" }
```

**Comment by jsmith9999d** [comment]
@tomstoneham that does indeed work, thanks. seems like two revisions need bumped then here with #758 to not need `git` in `Cargo.toml`?

i  think there shouldnt be fear of updating/version bumps just because some choose to stay on old vulnerable version of things and not update. may as well release to help those who care about staying secure and up to date rather than laggards.

**Comment by radan-jullien** [comment]
@djc @Kijewski new versions coming soon? i have same issue as others and using git in cargo.toml work but not great workaround

**Comment by fomigas131a** [comment]
@djc as reqest via zulip since you said its not support channel. any new version for this fix yet? you said to use github issue but issue not responded to in weeks. is there a better way to get update on issue if not here or zulip? seems many people, and me as new askama user, having this issue and waiting on fix on crates to easy install this and pass audits on deps.

**Comment by tom25519** [comment]
@fomigas131a Please keep in mind that (I assume) the maintainers of this repo do so for free. It can be frustrating waiting for a fix, but you don't know what other things may be going on which are blocking this issue behind the scenes, and being kind costs nothing :)

**Comment by fomigas131a** [comment]
@tom25519 oh yeah i know i wasnt trying to push just adding a comment to get any info as he mentioned on zulip. hope he is fine but also doesnt hurt to let people know whats up where possible and not leave them hanging for weeks.

**Comment by fomigas131a** [comment]
@djc thanks for that, without knowing that is what you are waiting on nobody would have relied to that effect as not mind reading.

i did try `0.11.x` as the branch and have no `cargo audit` issue or other error from `rust-analyzer`. my app compiles and runs fine. i would say version can bump and release which should resolve issue people are reporting here with the private export now public.

**Comment by djc** [comment]
Sorry about taking so long on this. I've published askama_axum 0.2.1 which I think resolves the issue.
