### PR TITLE
askama_axum: re-export BoxBody for compatibility

### LINKED ISSUE #757: askama_axum v0.2 error with Template
after update askama_axum to 0.2 (ref #756) i get following error and with the propose use statement

```
error[E0412]: cannot find type `BoxBody` in crate `askama_axum`
  --> mycrate\src\main.rs:11:10
   |
11 | #[derive(Template)]
   |          ^^^^^^^^ not found in `askama_axum`
   |
   = note: this error originates in the derive macro `Template` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this type alias
   |
1  | use axum::body::BoxBody;
   |
help: if you import `BoxBody`, refer to it directly
   |
11 | #[derive(Template)]
```

code similar to example at https://github.com/djc/askama/blob/main/askama_axum/tests/basic.rs

error on `#[derive(Template)]`

```
use askama::Template;
use axum::{
    extract,
    http::StatusCode,
    response::{Html, IntoResponse, Response},
    routing::{get, MethodRouter},
    Router,
};

#[derive(Template)]
#[template(path = "hello.html")]
struct HelloTemplate {
    name: String,
}
```

is why `cargo upgrade` mark update incompatible?

```
name        old req compatible latest new req note        
====        ======= ========== ====== ======= ====
anyhow      1.0.68  1.0.68     1.0.68 1.0.68
askama      0.11.1  0.11.1     0.11.1 0.11.1
askama_axum 0.1.0   0.1.0      0.2.0  0.1.0   incompatible
axum        0.6.1   0.6.1      0.6.1  0.6.1
tokio       1.23.0  1.23.0     1.23.0 1.23.0
```

### PR DESCRIPTION
**Pull request by djc**
Fixes #757, hopefully?

### CODE REVIEW

**Review by Kijewski — APPROVED** [review]
Seems to fix the problem. I move the `askama_axum` folder out of its workspace and removed `workspace = …` and `path = …` from its Cargo.toml to get the "freestanding experience".
